Feature/feature notification
Grupo13-PES-Mascotas/PES_My-Pet-Care pull request #69
Opened 2020-04-23 19:30 UTC by danicm47

2020-04-23 19:30 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Event.java  12
         

Coverage decreased per file
===========================
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Meals.java  -2
         

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPeriodicNotification.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeletePeriodicNotification.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PeriodEvent.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPeriodicNotification.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeletePeriodicNotification.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036&bid=17740261)

2020-04-23 19:40 UTC, AlbertPG requested changes
You should implement the access to the services

2020-04-23 19:40 UTC, AlbertPG commented on app/src/main/java/org/pesmypetcare/mypetcare/services/PetManagerAdapter.java
> +    public void registerNewPeriodicNotification(User user, Pet pet, Event event, int period) {
You should implement the access to the library

2020-04-23 22:34 UTC, santidrj commented on app/src/main/java/org/pesmypetcare/mypetcare/services/PetManagerService.java
> +    void registerNewPeriodicNotification(User user, Pet pet, Event event, int period) throws ParseException, ExecutionException, InterruptedException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 150).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036)

2020-04-23 22:34 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeletePeriodicNotification.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PeriodEvent.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeletePeriodicNotification.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPeriodicNotification.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPeriodicNotification.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036&bid=17740261)

2020-04-23 22:34 UTC, santidrj commented on app/src/main/java/org/pesmypetcare/mypetcare/services/PetManagerService.java
> +    void deletePeriodicEvent(User user, Pet pet, Event event) throws ParseException, ExecutionException, InterruptedException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 126).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036)

2020-04-24 00:05 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPeriodicNotification.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PeriodEvent.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPeriodicNotification.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeletePeriodicNotification.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeletePeriodicNotification.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036&bid=17740261)

2020-04-25 18:37 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPeriodicNotification.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPeriodicNotification.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PeriodEvent.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeletePeriodicNotification.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeletePeriodicNotification.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036&bid=17740261)

2020-04-26 09:46 UTC, AlbertPG approved these changes
Okey, I approve it

2020-04-26 09:46 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeletePeriodicNotification.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PeriodEvent.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeletePeriodicNotification.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPeriodicNotification.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPeriodicNotification.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036&bid=17740261)

2020-04-26 10:00 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPeriodicNotification.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeletePeriodicNotification.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPeriodicNotification.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeletePeriodicNotification.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PeriodEvent.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5411036&bid=17740261)

2020-04-26 10:06 UTC, merged